package require -exact qsys 12.1
set_validation_property AUTOMATIC_VALIDATION false

add_instance squeezenet_system squeezenet_system

add_connection acl_iface.kernel_clk squeezenet_system.clock_reset
add_connection acl_iface.kernel_clk2x squeezenet_system.clock_reset2x
add_connection acl_iface.kernel_reset squeezenet_system.clock_reset_reset

add_connection squeezenet_system.avm_memgmem0_port_0_0_rw acl_iface.kernel_mem0
add_connection acl_iface.kernel_irq squeezenet_system.kernel_irq

add_instance cra_root cra_ring_root
set_instance_parameter_value cra_root ASYNC_RESET 1
set_instance_parameter_value cra_root SYNCHRONIZE_RESET 0
set_instance_parameter_value cra_root DATA_W 64
set_instance_parameter_value cra_root ADDR_W 5
set_instance_parameter_value cra_root ID_W 2
add_connection acl_iface.kernel_clk cra_root.clock
add_connection acl_iface.kernel_reset cra_root.reset
add_connection acl_iface.kernel_cra cra_root.cra_slave
set_connection_parameter_value acl_iface.kernel_cra/cra_root.cra_slave baseAddress "0x0"
add_instance avs_avgpool2d_cra_cra_ring cra_ring_node
set_instance_parameter_value avs_avgpool2d_cra_cra_ring ASYNC_RESET 1
set_instance_parameter_value avs_avgpool2d_cra_cra_ring SYNCHRONIZE_RESET 0
set_instance_parameter_value avs_avgpool2d_cra_cra_ring DATA_W 64
set_instance_parameter_value avs_avgpool2d_cra_cra_ring RING_ADDR_W 5
set_instance_parameter_value avs_avgpool2d_cra_cra_ring CRA_ADDR_W 4
set_instance_parameter_value avs_avgpool2d_cra_cra_ring ID_W 2
set_instance_parameter_value avs_avgpool2d_cra_cra_ring ID 0
add_connection acl_iface.kernel_clk avs_avgpool2d_cra_cra_ring.clock
add_connection acl_iface.kernel_reset avs_avgpool2d_cra_cra_ring.reset
add_connection cra_root.ring_out avs_avgpool2d_cra_cra_ring.ring_in
add_connection avs_avgpool2d_cra_cra_ring.cra_master squeezenet_system.avs_avgpool2d_cra
set_connection_parameter_value avs_avgpool2d_cra_cra_ring.cra_master/squeezenet_system.avs_avgpool2d_cra baseAddress "0x0"
add_instance avs_conv2d1x1_cra_cra_ring cra_ring_node
set_instance_parameter_value avs_conv2d1x1_cra_cra_ring ASYNC_RESET 1
set_instance_parameter_value avs_conv2d1x1_cra_cra_ring SYNCHRONIZE_RESET 0
set_instance_parameter_value avs_conv2d1x1_cra_cra_ring DATA_W 64
set_instance_parameter_value avs_conv2d1x1_cra_cra_ring RING_ADDR_W 5
set_instance_parameter_value avs_conv2d1x1_cra_cra_ring CRA_ADDR_W 5
set_instance_parameter_value avs_conv2d1x1_cra_cra_ring ID_W 2
set_instance_parameter_value avs_conv2d1x1_cra_cra_ring ID 1
add_connection acl_iface.kernel_clk avs_conv2d1x1_cra_cra_ring.clock
add_connection acl_iface.kernel_reset avs_conv2d1x1_cra_cra_ring.reset
add_connection avs_avgpool2d_cra_cra_ring.ring_out avs_conv2d1x1_cra_cra_ring.ring_in
add_connection avs_conv2d1x1_cra_cra_ring.cra_master squeezenet_system.avs_conv2d1x1_cra
set_connection_parameter_value avs_conv2d1x1_cra_cra_ring.cra_master/squeezenet_system.avs_conv2d1x1_cra baseAddress "0x0"
add_instance avs_conv2d3x3_cra_cra_ring cra_ring_node
set_instance_parameter_value avs_conv2d3x3_cra_cra_ring ASYNC_RESET 1
set_instance_parameter_value avs_conv2d3x3_cra_cra_ring SYNCHRONIZE_RESET 0
set_instance_parameter_value avs_conv2d3x3_cra_cra_ring DATA_W 64
set_instance_parameter_value avs_conv2d3x3_cra_cra_ring RING_ADDR_W 5
set_instance_parameter_value avs_conv2d3x3_cra_cra_ring CRA_ADDR_W 5
set_instance_parameter_value avs_conv2d3x3_cra_cra_ring ID_W 2
set_instance_parameter_value avs_conv2d3x3_cra_cra_ring ID 2
add_connection acl_iface.kernel_clk avs_conv2d3x3_cra_cra_ring.clock
add_connection acl_iface.kernel_reset avs_conv2d3x3_cra_cra_ring.reset
add_connection avs_conv2d1x1_cra_cra_ring.ring_out avs_conv2d3x3_cra_cra_ring.ring_in
add_connection avs_conv2d3x3_cra_cra_ring.cra_master squeezenet_system.avs_conv2d3x3_cra
set_connection_parameter_value avs_conv2d3x3_cra_cra_ring.cra_master/squeezenet_system.avs_conv2d3x3_cra baseAddress "0x0"
add_instance avs_maxpool2d_cra_cra_ring cra_ring_node
set_instance_parameter_value avs_maxpool2d_cra_cra_ring ASYNC_RESET 1
set_instance_parameter_value avs_maxpool2d_cra_cra_ring SYNCHRONIZE_RESET 0
set_instance_parameter_value avs_maxpool2d_cra_cra_ring DATA_W 64
set_instance_parameter_value avs_maxpool2d_cra_cra_ring RING_ADDR_W 5
set_instance_parameter_value avs_maxpool2d_cra_cra_ring CRA_ADDR_W 4
set_instance_parameter_value avs_maxpool2d_cra_cra_ring ID_W 2
set_instance_parameter_value avs_maxpool2d_cra_cra_ring ID 3
add_connection acl_iface.kernel_clk avs_maxpool2d_cra_cra_ring.clock
add_connection acl_iface.kernel_reset avs_maxpool2d_cra_cra_ring.reset
add_connection avs_conv2d3x3_cra_cra_ring.ring_out avs_maxpool2d_cra_cra_ring.ring_in
add_connection avs_maxpool2d_cra_cra_ring.cra_master squeezenet_system.avs_maxpool2d_cra
set_connection_parameter_value avs_maxpool2d_cra_cra_ring.cra_master/squeezenet_system.avs_maxpool2d_cra baseAddress "0x0"
add_connection avs_maxpool2d_cra_cra_ring.ring_out cra_root.ring_in


save_system
